name: Run Selenium Tests and Send Allure Report Link

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest allure-pytest

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxvf allure-2.24.0.tgz
          sudo mv allure-2.24.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Run tests and generate Allure results
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Zip Allure Report
        run: |
          zip -r allure-report.zip allure-report

      - name: Upload Allure Report ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report.zip

      - name: Send Allure Report Email (link only)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtppro.zoho.in
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: ${{ secrets.EMAIL_USERNAME }}
          to: shubhamkohli2002@gmail.com, shubham.kohli@simplefixit.com
          subject: "🧪 Allure Test Report - ${{ github.run_id }}"
          body: |
            Hello,

            The scheduled test run has completed successfully.

            ✅ The Allure report is available as an artifact here:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            (Click the run, scroll to 'Artifacts', and download `allure-report.zip`)

            Regards,  
            Selenium Bot
